### ISSUE TITLE
Improve feedback when adding card to a collection

### ISSUE THREAD

**Issue by MrAGi** [AlanOC91/VangardCard#3]
When adding a card to your collection from the card database it is not clear that clicking on the save card button multiple times will add the card multiple times to your collection.

In addition, when it is clicked for the first time it goes grey but you can still click on it.

<img width="1229" alt="Screenshot 2021-07-12 at 16 09 47" src="https://user-images.githubusercontent.com/1733339/125311839-a407b700-e32b-11eb-99d3-3f556e611396.png">

**Comment by AlanOC91** [comment]
This wasn't intended. Now when you click it, it will only allow you to click it once and will only add 1 copy of the card (it will update the quantity by 1 if you already have the card in your collection).

This fix has now been rolled out.

I've also fixed an issue where you couldn't delete a card from your collection.
