### ISSUE TITLE
Easily add starter decks in single click

### ISSUE THREAD

**Issue by MrAGi** [AlanOC91/VangardCard#6]
When adding starter decks to your collection you should be able to do so in a single click rather than adding individual cards.

**Comment by AlanOC91** [comment]
I could maybe add a button to the pack page (when viewing a pack) that will upload the entire pack to your collection.

**Comment by AlanOC91** [comment]
Full Packs can now be added:

![Screenshot 2021-07-13 202710](https://user-images.githubusercontent.com/37552458/125513144-362a1489-69ee-4823-a828-760c401b1787.png)
