### ISSUE TITLE
Add cards from specific sets

### ISSUE THREAD

**Issue by MrAGi** [AlanOC91/VangardCard#7]
Currently when adding cards to your collection they show up under what looks like the most recent set that they are from rather than the set that they are owned from.

From example, I have Aurora Battle Princess, Amy Orange from the starter deck not Festival Collection:

<img width="1710" alt="Screenshot 2021-07-12 at 16 22 45" src="https://user-images.githubusercontent.com/1733339/125313781-7a4f8f80-e32d-11eb-8f7b-7cae36ecd863.png">
<img width="1710" alt="Screenshot 2021-07-12 at 16 23 36" src="https://user-images.githubusercontent.com/1733339/125313834-88051500-e32d-11eb-9093-cbb5f26f5081.png">

**Comment by AlanOC91** [comment]
This will require a bigger fix but I know what way I will do it. I will add a small upload icon next to each set on the card page. Clicking on this will add the card from that set rather than having it fall back to the first set every time.

**Comment by AlanOC91** [comment]
Icon now added. This allows you to upload a card from that particular set on the card page.

![Screenshot 2021-07-13 201334](https://user-images.githubusercontent.com/37552458/125511663-87661287-d7d2-44f1-9235-0a3d3aa52e81.png)

The collection manager also now reflects that. Currently, cards added to the collection previous to this will have a fallback set to the first one found.

![Screenshot 2021-07-13 201349](https://user-images.githubusercontent.com/37552458/125511677-ea2e2eaf-2c0e-40bb-a8a4-050c549b6ad4.png)
