### ISSUE TITLE
Added the same card from different sets to your collection doesn’t appear to work

### ISSUE THREAD

**Issue by MrAGi** [AlanOC91/VangardCard#9]
I was trying to update my collection to add cards based on fix for #7 but it does not appear to work fully.

For example the card Actual Analyst, Kokabiel is listed in my collection as from D Promo Cards but it should be from Genesis of the Five Greats.

From my collection page I clicked on the card and the clicked on the new button to add the card from the correct set.

I was expecting to see two listings in my collection for this card - one for each set.

Instead I am still just seeing the D Promo Card listing.

I haven’t tried deleting the card and readding but this isn’t a solution as you could definitely have the same card from multiple sets in your collection.

**Comment by AlanOC91** [comment]
This was a small bug on the card page I accidentally introduced yesterday that was causing a 400 error when attempting to add a card to the collection.

This is resolved now.
